CC = gcc

OUT1 = Supermercado.exe
FUENTE1 = Supermercado.c

COLA_DIN = '.\Cola Dinamica\TADColaDin.c'
COLA_EST = '.\Cola Estatica\TADColaEst.c'

Presentacion = ./Presentacion/presentacionWin.c


all:
	$(CC) -o $(OUT1) $(FUENTE1) $(COLA_DIN) $(Presentacion)

super_din:
	$(CC) -o $(OUT1) $(FUENTE1) $(COLA_DIN) $(Presentacion)
super_est:
	$(CC) -o $(OUT1) $(FUENTE1) $(COLA_EST) $(Presentacion)



